=== alexgv95/SW2/xml/galaxia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
       <xs:element name="Galaxia">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="Planetas">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Planeta" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                               <xs:sequence>
                                                                      <xs:element name="nombre" type="xs:string"></xs:element>
                                                                      <xs:element name="edad" type="xs:int"></xs:element>
                                                                      <xs:element name="radio" type="xs:double"></xs:element>
                                                                  </xs:sequence>
                                                           </xs:complexType>
                                                    </xs:element>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                        </xs:sequence>
                 </xs:complexType>
          </xs:element>
   </xs:schema>

=== alexgv95/SW2/xml/galaxiaXSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<Galaxia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="galaxia.xsd">
    <nombre>VÃ­a Lactea</nombre>
    <Planetas>
        <Planeta>
            <nombre>Tierra</nombre>
            <edad>4543</edad>
            <radio>6371.0</radio>
        </Planeta>
        <Planeta>
            <nombre>Marte</nombre>
            <edad>4603</edad>
            <radio>3390.0</radio>
        </Planeta>
        <Planeta>
            <nombre>Jupiter</nombre>
            <edad>4325</edad>
            <radio>26543.35</radio>
        </Planeta>
    </Planetas>
</Galaxia>
